---
title: "Reproducible Document"
author: "rostools"
format: html
---

```{r setup}
#| message: false
#| warning: false

library(tidyverse)

post_meal_data <- read_csv2(here::here("data/post-meal-insulin.csv"))
```

## About me
- Line 
- FGM
I am a *PHD student* in **Kim Ravnskjaer** lab 

```{r}
3 * 3
```



## Writing R code 

2 + 2 

```{r}
2 + 2
```

## Testing for Git
Sol i øjne

## Showing the data 
```{r}
post_meal_data

glimpse(post_meal_data)
```

## Plot one continious variable 

```{r}
#| fig-cap: "Distribution of BMI"
#| label: fig-BMI-histo
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```

See @fig-BMI-histo

## Exercise: discrete plots
```{r}
#| fig-cap: "Group bar plot"
#| label: fig-group-bar
ggplot(post_meal_data, aes(x = Group)) +
  geom_bar()
```

See @fig-group-bar above for a cool plot!

## Plotting two discrete variables 

```{r}
ggplot(post_meal_data, aes(x = Group, fill = as.character(glykemi))) +
  geom_bar(position = position_dodge())
```


## Side by side plots 

```{r fig-bmi-glycemia}
#| fig-cap: "BMI and Glycemia, side by side"
#| fig-subcap:
#|  - "Distribution of BMI"
#|  - "Number of those with glycemia"
#| layout-ncol: 2
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```

## Plotting two continous variables 
```{r}
#| fig-cap: "Scatterpllot of BMI and area under the curve for glucose"
#| label: fig-bmi-auc-pg
ggplot(post_meal_data, aes(x = BMI, y = auc_pg)) +
  geom_point() +
  geom_smooth()
```
